### ISSUE TITLE
osu irc not connected

### ISSUE THREAD

**Issue by aeongdesu** [aticie/ronnia#40]
It happens when sending beatmap link

- code
```
23/02/2022 08:58:43 | INFO | 1 | ronnia | send_message | Sending request in-game to STREAMER_OSU: [SUB] NICKNAME -> [Ranked] [http://osu.ppy.sh/b/3153134 Poppin'Party - Koko kara Saki wa Uta ni Naranai (TV Size) [Extra]] (190 BPM, 5.68*, 1:27)  
23/02/2022 08:58:43 | INFO | 1 | ronnia | _update_channel | Updating user with the latest news!
23/02/2022 08:58:43 | INFO | 1 | ronnia | handle_request | STREAMER - NICKNAME: https://osu.ppy.sh/beatmapsets/1542576#osu/3153134
    await self._send_irc_message(message, beatmap_info, given_mods)
    self.irc_bot.send_message(irc_target_channel, irc_message)
  File "/src/bots/irc_bot.py", line 55, in send_message
    self.connection.privmsg(target, cmd)
  File "/usr/local/lib/python3.9/site-packages/irc/client.py", line 564, in privmsg
    self.send_items('PRIVMSG', target, ':' + text)
  File "/usr/local/lib/python3.9/site-packages/irc/client.py", line 595, in send_items
    self.send_raw(' '.join(filter(None, items)))
  File "/usr/local/lib/python3.9/site-packages/jaraco/functools.py", line 306, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/irc/client.py", line 603, in send_raw
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/twitchio/client.py", line 193, in wrapped
    await func(*args)
  File "/src/bots/twitch_bot.py", line 77, in event_message
    await self.handle_request(message)
  File "/src/bots/twitch_bot.py", line 95, in handle_request
  File "/src/bots/twitch_bot.py", line 278, in _send_irc_message
irc.client.ServerNotConnectedError: Not connected.
    raise ServerNotConnectedError("Not connected.")
```

**Comment by aticie** [comment]
Hey there, could you re-check these environment variables, and make sure they are correct?

```
OSU_USERNAME=**** # Change this to your osu! username
IRC_PASSWORD=****  # Get yours from here: https://osu.ppy.sh/p/irc
```

**Comment by aeongdesu** [comment]
@aticie yes, I rechecked again and it is correct

**Comment by aticie** [comment]
Does "Successfully joined irc!" pop up in the logs? 

Also, are you using the master branch? If so, could you try using a tagged version, say v1.4.7?

**Comment by aeongdesu** [comment]
It works on v1.4.7, thanks.
there was no pop up in logs i think :(

**Comment by aticie** [comment]
I think I made some breaking changes on the master branch. Sorry for that.

 It will all be changed after I merge the `Feature/multiple-instances` branch anyway.
